---
# Depending on enablement of individual excluders and their status
# some excluders needs to be disabled, resp. enabled
# By default, all excluders are disabled unless overrided.
- block:
  - include: init.yml
  # All excluders that are to be enabled are enabled
  - include: exclude.yml
    vars:
      # Enable the docker excluder only if it is overrided
      # BZ #1430612: docker excluders should be enabled even during installation and upgrade
      exclude_docker_excluder: "{{ enable_docker_excluder | default(true) | bool }}"
      # excluder is to be disabled by default
      exclude_openshift_excluder: false
  # All excluders that are to be disabled are disabled
  - include: unexclude.yml
    vars:
      # If the docker override  is not set, default to the generic behaviour
      # BZ #1430612: docker excluders should be enabled even during installation and upgrade
      unexclude_docker_excluder: false
      # disable openshift excluder is never overrided to be enabled
      # disable it if the docker excluder is enabled
      unexclude_openshift_excluder: "{{ openshift_excluder_on | bool }}"
  when:
  - not openshift.common.is_atomic | bool
